"""add user_nodes table

Revision ID: 44b7d68fe1be
Revises: 4621a81a39b5
Create Date: 2025-11-12 23:18:41.432153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b7d68fe1be'
down_revision = '4621a81a39b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.alter_column('data_limit',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('expire_duration',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('sub_last_user_agent',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('sub_last_user_agent',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.alter_column('expire_duration',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('data_limit',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.drop_table('user_nodes')
    # ### end Alembic commands ###
